# Generated by Django 3.0.5 on 2020-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_path', models.CharField(max_length=120)),
                ('budget', models.CharField(max_length=120)),
                ('tmdb_id', models.CharField(max_length=120)),
                ('orginal_title', models.TextField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('popularity', models.TextField()),
                ('status', models.TextField()),
                ('release_date', models.TextField()),
                ('runtime', models.TextField()),
                ('tagline', models.TextField()),
                ('title', models.TextField()),
                ('video', models.TextField()),
                ('vote_average', models.TextField()),
                ('vote_count', models.TextField()),
            ],
        ),
    ]
